### ISSUE TITLE
Failures casting arrays with numpy 1.10

### ISSUE THREAD

**Issue by matthew-brett** [regreg/regreg#12]
Running some travis tests:

https://travis-ci.org/matthew-brett/regreg/jobs/98112406#L512

```
======================================================================
ERROR: regreg.problems.tests.test_nesta_path.test_lasso_path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python3.5/site-packages/regreg/problems/tests/test_nesta_path.py", line 16, in test_lasso_path
    sol1 = lasso1.main()
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python3.5/site-packages/regreg/paths.py", line 325, in main
    all_failing += strong_selector.adjoint_map(strong_failing)
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('bool') with casting rule 'same_kind'
```

This error is correct, because the code is trying to do an in-place add of a float (from the `adjoint_map` call) to a bool (in `all_failing`).  Should this be something like:

```
all_failing += strong_selector.adjoint_map(strong_failing) != 0
```

?

**Comment by matthew-brett** [comment]
Also:

```
======================================================================
ERROR: regreg.problems.tests.test_smooth_conjugate.test_quadratic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python2.6/site-packages/regreg/problems/tests/test_smooth_conjugate.py", line 16, in test_quadratic
    q2 = q1 + l.quadratic
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python2.6/site-packages/regreg/identity_quadratic.py", line 151, in __add__
    sc = self.collapsed()
  File "/home/travis/build/matthew-brett/regreg/venv/lib/python2.6/site-packages/regreg/identity_quadratic.py", line 211, in collapsed
    linear_term += self.linear_term
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```
https://travis-ci.org/matthew-brett/regreg/jobs/98118631

Maybe fix is to make `lnear_term` be floating point initially.

**Comment by matthew-brett** [comment]
Added a PR #13 with tentative fixes.
